web_student_Entreprise_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: webStudentEntrepriseBundle:Entreprise:index }
SalutEntreprise:
    pattern:  /salutEntreprise/{name}
    defaults: { _controller: webStudentEntrepriseBundle:Entreprise:index }
Entreprise_accueil:
    path:    /entreprise/accueil
    defaults: { _controller: webStudentEntrepriseBundle:Entreprise:index }
Entreprise_consulter:
    path:    /entreprise/consulter/{id}
    defaults: { _controller:webStudentEntrepriseBundle:Entreprise:consulter }
Entreprise_ajouter:
    path:    /entreprise/ajouter
    defaults: { _controller: webStudentEntrepriseBundle:Entreprise:ajouter }
Entreprise_modifier:
    path:    /entreprise/modifier
    defaults: { _controller: webStudentEntrepriseBundle:Entreprise:modifier }
Entreprise_consulterS:
    path:    /entreprise/consulterEntreprise
    defaults: { _controller: webStudentEntrepriseBundle:Entreprise:consulterEntreprise }
Entreprise_ajouterS:
    path:    /entreprise/ajouterEntreprise
    defaults: { _controller: webStudentEntrepriseBundle:Entreprise:ajouterEntreprise }
