parameters:
#    web_student_connexion.example.class: webStudent\ConnexionBundle\Example

services:
#    web_student_connexion.example:
#        class: %web_student_connexion.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
